# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Shayan Khorsandi
title: Software Engineer | Research Scientist
email: shn.khorsandi@gmail.com
phone: +98 - 912 084 3547
website: www.abradat.github.io

# Social links
#twitter_username: facespics
github_username:  abradat
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: thisishayan
linkedin_username: sh-khorsandi
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

#additional_links:
#  - title: CV
#    icon: fa-twitter
#    url: www.google.com
# About Section
# about_title: About Me
about_profile_image: images/profile_4.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name’s Shayan, and I’ve recently graduated with a Bachelor of Science in Computer Engineering from Iran University of Science and Technology. Right now, I am a software engineer at Informatics Services Corporation (ISC). 
  I was a research assistant at the Bio-Inspired System Design lab under the supervision of [Prof. Soroush Sadeghnejad](https://www.linkedin.com/in/soroush-sadeghnejad-a13aa888/) at the Amirkabir University of Technology. 
  Before that, I was a research assistant at the Robotics lab under the supervision of [Prof. Mohsen Bahrami](https://aut.ac.ir/cv/2297/Mohsen%20Bahrami) at the Amirkabir University of Technology.
# My research interests are <mark>Software Engineering</mark>, <mark>Human-Computer Interaction</mark> , and applications of <mark>Machine Learning</mark> in these areas.
# My <mark>CV</mark> is available through [here](https://drive.google.com/file/d/1LR-s-f8XEQCjyPmTnlSGrYSpq_axUVro/view?usp=sharing).
darkmode: never
# Projects Section
projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my academic and professional life, some of my hobbies are:
   - Gaming; I am a huge fan of [Hidetaka Miyazaki's](https://en.wikipedia.org/wiki/Hidetaka_Miyazaki) games.
   - Running
   - Movies

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
