# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Shayan Khorsandi
title: Software Engineer | Research Scientist
email: shn.khorsandi@gmail.com
phone: +98 - 912 084 3547
website: www.abradat.github.io

# Social links
#twitter_username: facespics
github_username:  abradat
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: thisishayan
linkedin_username: sh-khorsandi
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

additional_links:
  - title: CV
    icon: fa-twitter
    url: www.google.com
# About Section
# about_title: About Me
about_profile_image: images/profile_2.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  My research interest are: <mark>AWS</mark> and <mark>Eating Pizza</mark>

darkmode: true
# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Gaming; I am a huge fan of [Hidetaka Miyazaki's](https://en.wikipedia.org/wiki/Hidetaka_Miyazaki) games.
   - Running
   - Movies: Anime test

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
