# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Shayan Khorsandi
title: Software Engineer | Research Scientist
email: shn.khorsandi@gmail.com
phone: +98 - 912 084 3547
website: www.abradat.github.io

# Social links
#twitter_username: facespics
github_username:  abradat
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: thisishayan
linkedin_username: sh-khorsandi
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

#additional_links:
#  - title: CV
#    icon: fa-twitter
#    url: www.google.com
# About Section
# about_title: About Me
about_profile_image: images/profile_2.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Shayan, and I'm a fresh B.Sc. graduate in computer engineering from Iran University of Science and Technology. Right now, I am a software engineer at Informatics Services Corporation (ISC).
  Also, I was research assistant at Bio-Inspired System Design lab under supervison of [Prof. Soroush Sadeghnejad](https://www.linkedin.com/in/soroush-sadeghnejad-a13aa888/) in Amirkabir University of Technology.
  Before that I was research assistant at Robotics lab under supervision of [Prof. Mohsen Bahrami](https://aut.ac.ir/cv/2297/Mohsen%20Bahrami) at Amirkabir University of Technology.

  My research interests are <mark>Software Engineering</mark>, <mark>Human-Computer Interaction</mark> , and applications of <mark>Machine Learning</mark> in these areas.

  My <mark>CV</mark> is available through [here](www.google.com).
darkmode: false
# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Gaming; I am a huge fan of [Hidetaka Miyazaki's](https://en.wikipedia.org/wiki/Hidetaka_Miyazaki) games.
   - Running
   - Movies: Anime test

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
